# Stories for the Verbs tab: one per tense.
#
# Mark every conjugated verb with [brackets]. tools/stories/build.py looks the form up in verbs.json to find
# its verb, tense and person. When a form could be more than one thing, add a hint after a colon: the verb
# ([fue:ir]), the tense ([habla:cmd]) or the person ([era:yo]). Infinitives and everything else stay plain;
# build.py checks those words are in words.json (or are small words like el, que, muy).
#
# Dialogue uses « » so no dashes are needed.

STORIES = [
    {
        "tense": "pres",
        "title": "Un día normal",
        "titleEn": "An ordinary day",
        "sentences": [
            ("Ana [vive] en una ciudad pequeña con su familia.", "Ana lives in a small city with her family."),
            ("Todos los días se [levanta] temprano.", "Every day she gets up early."),
            ("[Come] pan con queso y [bebe] un café.", "She eats bread with cheese and drinks a coffee."),
            ("Después [sale] de casa y [toma] el autobús.", "Then she leaves home and takes the bus."),
            ("[Trabaja] en una oficina en el centro.", "She works in an office in the centre."),
            ("Su jefe [es] simpático, pero a veces [pide] demasiado.", "Her boss is nice, but sometimes he asks too much."),
            ("A la una, Ana y sus amigos [comen] en un restaurante cerca de la oficina.", "At one o'clock, Ana and her friends eat at a restaurant near the office."),
            ("Por la tarde [vuelve] a casa y [juega] con su perro.", "In the afternoon she goes back home and plays with her dog."),
            ("Su hermano Luis [cocina] la cena.", "Her brother Luis cooks dinner."),
            ("«¿Qué [haces] mañana?», [pregunta] Luis.", "\"What are you doing tomorrow?\" Luis asks."),
            ("«No [sé]. ¿[Quieres] ir al cine?», [dice] Ana.", "\"I don't know. Do you want to go to the cinema?\" Ana says."),
            ("«Sí, pero [tengo] poco dinero», [responde] Luis.", "\"Yes, but I have little money,\" Luis answers."),
            ("Por la noche Ana [lee] un libro y [duerme] ocho horas.", "At night Ana reads a book and sleeps eight hours."),
        ],
    },
    {
        "tense": "pret",
        "title": "Un día terrible",
        "titleEn": "A terrible day",
        "sentences": [
            ("Ayer Ana se [despertó] tarde.", "Yesterday Ana woke up late."),
            ("No [oyó] el teléfono y [perdió] el autobús.", "She didn't hear the phone and missed the bus."),
            ("[Salió] de casa sin comer y [llegó] a la oficina a las diez.", "She left home without eating and got to the office at ten."),
            ("Su jefe [estuvo] enojado toda la mañana.", "Her boss was angry all morning."),
            ("A la una, Ana [buscó] su teléfono, pero no lo [encontró].", "At one o'clock, Ana looked for her phone, but she didn't find it."),
            ("«¿Dónde [puse] mi teléfono?», [pensó].", "\"Where did I put my phone?\" she thought."),
            ("Por la tarde [llovió] mucho.", "In the afternoon it rained a lot."),
            ("Ana [volvió] a casa y [vio] su teléfono en la mesa.", "Ana went back home and saw her phone on the table."),
            ("Luis [hizo] una sopa y los dos [comieron] juntos.", "Luis made a soup and the two of them ate together."),
            ("«¿Qué tal tu día?», [preguntó] Luis.", "\"How was your day?\" Luis asked."),
            ("«Terrible, pero ya [pasó]», [dijo] Ana, y se [rio].", "\"Terrible, but it's over now,\" Ana said, and laughed."),
            ("«Yo [tuve] un día muy bueno», [contestó] Luis.", "\"I had a very good day,\" Luis answered."),
        ],
    },
    {
        "tense": "impf",
        "title": "Cuando éramos niños",
        "titleEn": "When we were children",
        "sentences": [
            ("Cuando Ana [era:el] niña, [vivía:el] con sus abuelos en el campo.", "When Ana was a little girl, she lived with her grandparents in the country."),
            ("La casa [estaba] cerca de un río y [tenía:el] un jardín grande.", "The house was near a river and had a big garden."),
            ("Todos los días su abuelo [trabajaba:el] en el campo y su abuela [cocinaba:el] pan.", "Every day her grandfather worked in the fields and her grandmother made bread."),
            ("Ana y su hermano [jugaban] con los animales.", "Ana and her brother played with the animals."),
            ("En verano [hacía:el] mucho calor y los niños [nadaban] en el río.", "In summer it was very hot and the children swam in the river."),
            ("En invierno a veces [nevaba].", "In winter it sometimes snowed."),
            ("Los domingos [íbamos] a la iglesia del pueblo.", "On Sundays we went to the village church."),
            ("Desde la ventana [veíamos] las montañas.", "From the window we could see the mountains."),
            ("Por la noche, la abuela [contaba:el] historias y todos [escuchaban] en silencio.", "At night, grandmother told stories and everyone listened in silence."),
            ("«[Éramos] muy felices», [dice] Ana ahora.", "\"We were very happy,\" Ana says now."),
            ("«No [teníamos] mucho dinero, pero no [necesitábamos] nada.»", "\"We didn't have much money, but we didn't need anything.\""),
        ],
    },
    {
        "tense": "fut",
        "title": "El viaje",
        "titleEn": "The trip",
        "sentences": [
            ("El próximo mes, Ana y Luis [harán] un viaje a la costa.", "Next month, Ana and Luis will take a trip to the coast."),
            ("[Saldrán] el viernes temprano y [viajarán] en tren.", "They'll leave early on Friday and travel by train."),
            ("[Llegarán] a un hotel pequeño cerca del mar.", "They'll arrive at a small hotel near the sea."),
            ("Ana [nadará] todos los días y Luis [leerá] en la playa.", "Ana will swim every day and Luis will read on the beach."),
            ("«[Tendremos] mucho tiempo para descansar», [dice] Ana.", "\"We'll have lots of time to rest,\" Ana says."),
            ("«Yo [podré] dormir hasta tarde», [dice] Luis.", "\"I'll be able to sleep late,\" Luis says."),
            ("Por la noche [comerán] pescado en un restaurante.", "In the evening they'll eat fish at a restaurant."),
            ("«¿[Vendrás] con nosotros?», le [pregunta] Ana a su madre.", "\"Will you come with us?\" Ana asks her mother."),
            ("«No [sé]. [Habrá] mucho trabajo en la oficina», [responde] ella.", "\"I don't know. There will be a lot of work at the office,\" she answers."),
            ("«Te [llamaré] cada noche y te [diré] todo», [dice] Ana.", "\"I'll call you every night and tell you everything,\" Ana says."),
        ],
    },
    {
        "tense": "cond",
        "title": "Con un millón de dólares",
        "titleEn": "With a million dollars",
        "sentences": [
            ("«¿Qué [harías] con un millón de dólares?», [pregunta] Luis.", "\"What would you do with a million dollars?\" Luis asks."),
            ("Ana [piensa] un momento.", "Ana thinks for a moment."),
            ("«[Compraría] una casa con jardín cerca del mar», [dice].", "\"I'd buy a house with a garden near the sea,\" she says."),
            ("«También [viajaría] por todo el mundo.»", "\"I'd also travel all over the world.\""),
            ("«Mis padres no [tendrían] que trabajar más.»", "\"My parents wouldn't have to work any more.\""),
            ("«¿Y tú?»", "\"And you?\""),
            ("«Yo [ayudaría] a la gente pobre de nuestro barrio», [responde] Luis.", "\"I'd help the poor people in our neighbourhood,\" Luis answers."),
            ("«[Abriría] una escuela para los niños.»", "\"I'd open a school for the children.\""),
            ("«Y [podríamos] ir juntos de vacaciones cada verano.»", "\"And we could go on holiday together every summer.\""),
            ("Ana se [ríe:pres]: «[Sería] perfecto. Pero primero [necesitaríamos] el millón.»", "Ana laughs: \"That would be perfect. But first we'd need the million.\""),
        ],
    },
    {
        "tense": "perf",
        "title": "Hoy ha sido un buen día",
        "titleEn": "Today has been a good day",
        "sentences": [
            ("Hoy [ha sido] un día muy bueno para Ana.", "Today has been a very good day for Ana."),
            ("Esta mañana [ha hablado] con su jefe y él le [ha dado] un proyecto nuevo.", "This morning she talked to her boss and he gave her a new project."),
            ("[Ha escrito] muchos correos y [ha trabajado] mucho, pero no [ha estado] cansada.", "She has written lots of emails and worked hard, but she hasn't been tired."),
            ("A la hora del almuerzo [ha visto] a su amiga Marta.", "At lunchtime she saw her friend Marta."),
            ("«¿[Has comido] ya?», le [ha preguntado] Marta.", "\"Have you eaten yet?\" Marta asked her."),
            ("«No, todavía no [he comido] nada», [ha dicho] Ana.", "\"No, I haven't eaten anything yet,\" Ana said."),
            ("Las dos [han ido] a un restaurante nuevo.", "The two of them went to a new restaurant."),
            ("Por la tarde Ana [ha vuelto] a casa temprano.", "In the afternoon Ana came home early."),
            ("Luis [ha hecho] la cena y [han abierto] una botella de vino.", "Luis has made dinner and they've opened a bottle of wine."),
            ("«Nunca [hemos comido] tan bien», [ha dicho] Luis.", "\"We've never eaten so well,\" Luis said."),
        ],
    },
    {
        "tense": "subj",
        "title": "Los consejos de la abuela",
        "titleEn": "Grandmother's advice",
        "sentences": [
            ("Ana [va] a vivir sola en otra ciudad, y su abuela [está] un poco preocupada.", "Ana is going to live on her own in another city, and her grandmother is a little worried."),
            ("«[Quiero] que me [llames] todas las semanas», [dice] la abuela.", "\"I want you to call me every week,\" grandmother says."),
            ("«[Espero] que [encuentres] buenos amigos.»", "\"I hope you find good friends.\""),
            ("«[Es] importante que [comas] bien y que [duermas] ocho horas.»", "\"It's important that you eat well and sleep eight hours.\""),
            ("«No [creo:creer] que [sea] fácil al principio.»", "\"I don't think it will be easy at first.\""),
            ("«Cuando [tengas] un problema, [habla:cmd] con tus vecinos.»", "\"When you have a problem, talk to your neighbours.\""),
            ("«Y ojalá [puedas] venir a casa en verano.»", "\"And I hope you can come home in the summer.\""),
            ("Ana se [ríe:pres]. «No te [preocupes], abuela. Todo [va] a estar bien.»", "Ana laughs. \"Don't worry, grandma. Everything is going to be fine.\""),
            ("La abuela le [da] un regalo: «Para que [recuerdes] tu casa.»", "Grandmother gives her a present: \"So that you remember your home.\""),
            ("«Ojalá que todo te [vaya] bien. Y cuando [vuelvas], [quiero] que [cocinemos] juntas.»", "\"I hope everything goes well for you. And when you come back, I want us to cook together.\""),
        ],
    },
    {
        "tense": "cmd",
        "title": "En la cocina",
        "titleEn": "In the kitchen",
        "sentences": [
            ("Luis [enseña:pres] a Ana a hacer una sopa.", "Luis teaches Ana to make a soup."),
            ("«Primero, [lava:cmd] las verduras», [dice] Luis.", "\"First, wash the vegetables,\" Luis says."),
            ("«[Corta:cmd] el tomate y la papa. ¡No [cortes] los dedos!»", "\"Cut the tomato and the potato. Don't cut your fingers!\""),
            ("«[Pon] el agua al fuego y [espera:cmd] diez minutos.»", "\"Put the water on the heat and wait ten minutes.\""),
            ("«Ahora [usa:cmd] la cuchara y [mueve:cmd] la sopa despacio.»", "\"Now use the spoon and stir the soup slowly.\""),
            ("«¡No [toques] el fuego!»", "\"Don't touch the heat!\""),
            ("Ana [prueba:pres] la sopa: «¡[Está:pres] muy rica!»", "Ana tastes the soup: \"It's delicious!\""),
            ("Entonces [llega:pres] su vecina.", "Then their neighbour arrives."),
            ("«[Pase], señora. [Pruebe] la sopa», [dice:pres] Ana.", "\"Come in. Try the soup,\" Ana says to her."),
            ("«[Comamos] juntos», [dice:pres] Luis.", "\"Let's eat together,\" Luis says."),
            ("Después de la cena, la vecina [sonríe:pres]: «Muy rica. Ahora [laven] los platos, por favor.»", "After dinner, the neighbour smiles: \"Delicious. Now wash the dishes, please.\""),
        ],
    },
    {
        "tense": "impsubj",
        "title": "El perro de Luis",
        "titleEn": "Luis's dog",
        "sentences": [
            ("Cuando Luis [era:el] pequeño, [quería:el] que su padre le [comprara:el] un perro.", "When Luis was little, he wanted his father to buy him a dog."),
            ("Su padre [decía:el]: «Si [tuviéramos] un jardín, [compraría:yo] un perro.»", "His father used to say: \"If we had a garden, I would buy a dog.\""),
            ("Pero [vivían] en un piso pequeño en el centro.", "But they lived in a small flat in the centre."),
            ("Luis [soñaba:el] con un perro que [corriera:el] con él por el parque.", "Luis dreamed of a dog that would run with him in the park."),
            ("Un día su madre le [dijo]: «[Quisiera:yo] que [entendieras] una cosa: un perro [necesita] mucho cuidado.»", "One day his mother told him: \"I'd like you to understand one thing: a dog needs a lot of care.\""),
            ("Luis [respondió]: «Si [tuviera:yo] un perro, lo [cuidaría:yo] cada día.»", "Luis answered: \"If I had a dog, I would look after it every day.\""),
            ("Para su cumpleaños, sus padres le [dieron] una sorpresa: un perro pequeño y negro.", "For his birthday, his parents gave him a surprise: a small black dog."),
            ("«¡Si [supieras] lo feliz que [estoy]!», [dijo] Luis.", "\"If you only knew how happy I am!\" Luis said."),
            ("Y [cuidó] al perro como si [fuera:ser] su hermano.", "And he looked after the dog as if it were his brother."),
        ],
    },
    {
        "tense": "plup",
        "title": "Demasiado tarde",
        "titleEn": "Too late",
        "sentences": [
            ("Cuando Ana [llegó] a la estación, el tren ya [había salido:el].", "When Ana got to the station, the train had already left."),
            ("Esa noche no [había dormido:el] bien y se [había olvidado:el] de mirar la hora.", "That night she hadn't slept well and she had forgotten to check the time."),
            ("[Llamó] a Luis, pero él también [había salido:el] de casa.", "She called Luis, but he had left home too."),
            ("«¿Por qué no me [habías dicho] que el tren [salía:el] a las ocho?», le [preguntó].", "\"Why hadn't you told me the train left at eight?\" she asked him."),
            ("«Te lo [había dicho:yo] dos veces», [respondió] Luis.", "\"I had told you twice,\" Luis answered."),
            ("Ana [recordó] que él [había escrito:el] la hora en un papel.", "Ana remembered that he had written the time on a piece of paper."),
            ("Pero ella [había perdido:el] el papel.", "But she had lost the paper."),
            ("Por suerte, [encontró] un autobús que [iba:el] a la misma ciudad.", "Luckily, she found a bus that was going to the same city."),
            ("Cuando [llegó], sus amigos ya [habían empezado] la fiesta sin ella.", "When she arrived, her friends had already started the party without her."),
            ("«¡Nunca te [habíamos visto] llegar tarde!», [dijeron].", "\"We'd never seen you arrive late!\" they said."),
        ],
    },
    {
        "tense": "futperf",
        "title": "Los planes de Ana",
        "titleEn": "Ana's plans",
        "sentences": [
            ("Ana [tiene] muchos planes para este año.", "Ana has lots of plans for this year."),
            ("«Para el verano, [habré terminado] mi curso de inglés», [dice].", "\"By the summer, I'll have finished my English course,\" she says."),
            ("«Para el otoño, Luis y yo [habremos pintado] el apartamento.»", "\"By the autumn, Luis and I will have painted the flat.\""),
            ("«Y mis padres [habrán vuelto] de su viaje.»", "\"And my parents will have come back from their trip.\""),
            ("«Y tú, ¿[habrás encontrado] un trabajo nuevo?», le [pregunta] a Luis.", "\"And you, will you have found a new job?\" she asks Luis."),
            ("«Eso [espero]. Para el invierno, [habré ganado] más dinero», [responde] él.", "\"I hope so. By the winter, I'll have earned more money,\" he answers."),
            ("Luis [mira] la puerta: «¿Dónde [está] Marta? [Habrá perdido] el autobús.»", "Luis looks at the door: \"Where's Marta? She must have missed the bus.\""),
            ("Media hora después, Marta [llega].", "Half an hour later, Marta arrives."),
            ("«Perdón, [he perdido] el autobús», [dice].", "\"Sorry, I missed the bus,\" she says."),
        ],
    },
    {
        "tense": "condperf",
        "title": "La otra vida de Pablo",
        "titleEn": "Pablo's other life",
        "sentences": [
            ("Hace diez años, Pablo [tuvo] que elegir entre dos trabajos.", "Ten years ago, Pablo had to choose between two jobs."),
            ("[Eligió] un trabajo en un banco de la ciudad.", "He chose a job at a bank in the city."),
            ("Ahora a veces [piensa] en el otro trabajo, en una escuela del campo.", "Now he sometimes thinks about the other job, at a school in the country."),
            ("«Si [hubiera elegido:yo] la escuela, [habría vivido:yo] cerca de las montañas», [dice].", "\"If I had chosen the school, I would have lived near the mountains,\" he says."),
            ("«[Habría tenido:yo] menos dinero, pero más tiempo.»", "\"I would have had less money, but more time.\""),
            ("«Mis hijos [habrían crecido] con los animales.»", "\"My children would have grown up with the animals.\""),
            ("«Mi esposa y yo [habríamos estado] más tranquilos.»", "\"My wife and I would have been calmer.\""),
            ("Su esposa [escucha] y [sonríe].", "His wife listens and smiles."),
            ("«Y tú, ¿qué [habrías hecho]?», le [pregunta] Pablo.", "\"And you, what would you have done?\" Pablo asks her."),
            ("«Yo [habría elegido:yo] lo mismo. Si no, no nos [habríamos conocido] en el banco.»", "\"I would have chosen the same. Otherwise, we wouldn't have met at the bank.\""),
        ],
    },
    {
        "tense": "subjperf",
        "title": "El examen de Marta",
        "titleEn": "Marta's test",
        "sentences": [
            ("Hoy Marta [tiene] su examen de conducir.", "Today Marta has her driving test."),
            ("Su madre [está] nerviosa en casa.", "Her mother is nervous at home."),
            ("«[Espero] que [haya llegado:el] a tiempo», [dice].", "\"I hope she got there on time,\" she says."),
            ("«Ojalá que [haya dormido:el] bien.»", "\"I hope she slept well.\""),
            ("Su padre [responde]: «No [creo:creer] que [haya tenido:el] problemas. [Es] muy buena.»", "Her father answers: \"I don't think she's had any problems. She's very good.\""),
            ("Por la tarde, Marta [llama] por teléfono: «No [sé]. Es posible que [haya ido:yo] demasiado rápido.»", "In the afternoon, Marta calls: \"I don't know. Maybe I went too fast.\""),
            ("Media hora después [llega] un mensaje: ¡[Ha pasado] el examen!", "Half an hour later a message arrives: she's passed the test!"),
            ("«[Estoy] muy contenta de que lo [hayas conseguido]», [dice] su madre.", "\"I'm so glad you did it,\" her mother says."),
            ("Su padre se [ríe:pres]: «¿[Ves]? No [creo:creer] que [hayamos tenido] razones para estar nerviosos.»", "Her father laughs: \"See? I don't think we had any reason to be nervous.\""),
        ],
    },
    {
        "tense": "plupsubj",
        "title": "Si lo hubiera sabido",
        "titleEn": "If I had known",
        "sentences": [
            ("El sábado Luis [fue:ir] a la playa con sus amigos.", "On Saturday Luis went to the beach with his friends."),
            ("No [llevó] chaqueta y de repente [empezó] a llover.", "He didn't take a jacket and suddenly it started to rain."),
            ("[Volvió] a casa mojado y con frío.", "He came home wet and cold."),
            ("«Si [hubiera mirado:yo] el tiempo, [habría llevado:yo] una chaqueta», [dijo].", "\"If I had checked the weather, I would have taken a jacket,\" he said."),
            ("Su madre [contestó]: «Si me [hubieras preguntado], te lo [habría dicho:yo].»", "His mother answered: \"If you had asked me, I would have told you.\""),
            ("Al día siguiente Luis [estaba:el] enfermo.", "The next day Luis was ill."),
            ("«Si [hubieras llevado] la chaqueta, no [estarías] enfermo», le [dijo] su madre.", "\"If you had taken the jacket, you wouldn't be ill,\" his mother told him."),
            ("«Ojalá [hubiera escuchado:yo] a mi madre», [pensó].", "\"I wish I had listened to my mother,\" he thought."),
            ("Sus amigos lo [llamaron]: «Si [hubiéramos sabido] que [estabas] enfermo, [habríamos venido] antes.»", "His friends called him: \"If we had known you were ill, we would have come sooner.\""),
            ("Luis se [rio:pret]: «No [pasa] nada. La próxima vez [miraré] el tiempo.»", "Luis laughed: \"It doesn't matter. Next time I'll check the weather.\""),
        ],
    },
]
